package com.notificationservice.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Request DTO for widget initialization.
 *
 * @param visitorId unique identifier for the visitor (generated by the widget)
 * @param screenWidth visitor's screen width in pixels
 * @param screenHeight visitor's screen height in pixels
 * @param language visitor's browser language (e.g., "en-US")
 * @param timezone visitor's IANA timezone (e.g., "America/New_York")
 */
public record WidgetInitRequest(
        @NotBlank @Size(max = 255) String visitorId,
        Integer screenWidth,
        Integer screenHeight,
        @Size(max = 16) String language,
        @Size(max = 64) String timezone
) {}
