package com.notificationservice.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Request DTO for widget initialization.
 *
 * @param visitorId unique identifier for the visitor (generated by the widget)
 */
public record WidgetInitRequest(
        @NotBlank @Size(max = 255) String visitorId
) {}